var phrases = [
    { pt: 'Qual é o seu nome?', en: 'What is your name?' },
    { pt: 'Qual é a sua idade?', en: 'How old are you?' },
    { pt: 'Qual é a sua profissão?', en: 'What is your profession?' },
    { pt: 'Qual é o seu endereço?', en: 'What is your address?' },
    { pt: 'Qual é o seu número de telefone?', en: 'What is your phone number?' },
    { pt: 'Qual é a sua nacionalidade?', en: 'What is your nationality?' },
    { pt: 'Qual é o seu time de futebol favorito?', en: 'What is your favorite soccer team?' },
    { pt: 'Qual é a data de hoje?', en: 'What is today\'s date?' },
    { pt: 'Qual é o seu filme favorito?', en: 'What is your favorite movie?' },
    { pt: 'Qual é a sua comida favorita?', en: 'What is your favorite food?' },
    { pt: 'Onde você mora?', en: 'Where do you live?' },
    { pt: 'Onde você trabalha?', en: 'Where do you work?' },
    { pt: 'Onde está o banheiro?', en: 'Where is the bathroom?' },
    { pt: 'Onde fica a estação de trem?', en: 'Where is the train station?' },
    { pt: 'Onde você nasceu?', en: 'Where were you born?' },
    { pt: 'Onde está o restaurante?', en: 'Where is the restaurant?' },
    { pt: 'Onde está o supermercado mais próximo?', en: 'Where is the nearest supermarket?' },
    { pt: 'Onde você estudou?', en: 'Where did you study?' },
    { pt: 'Onde está o ponto de ônibus?', en: 'Where is the bus stop?' },
    { pt: 'Onde você estava ontem?', en: 'Where were you yesterday?' } ,

    { pt: 'Meu nome é João.', en: 'My name is João.' },
    { pt: 'Eu tenho 25 anos.', en: 'I am 25 years old.' },
    { pt: 'Eu sou engenheiro.', en: 'I am an engineer.' },
    { pt: 'Meu endereço é Rua das Flores, 123.', en: 'My address is 123 Flowers Street.' },
    { pt: 'Meu número de telefone é (11) 98765-4321.', en: 'My phone number is (11) 98765-4321.' },
    { pt: 'Eu sou brasileiro.', en: 'I am Brazilian.' },
    { pt: 'Meu time de futebol favorito é o Flamengo.', en: 'My favorite soccer team is Flamengo.' },
    { pt: 'Hoje é 11 de junho de 2024.', en: 'Today is June 11, 2024.' },
    { pt: 'Meu filme favorito é "O Poderoso Chefão".', en: 'My favorite movie is "The Godfather".' },
    { pt: 'Minha comida favorita é pizza.', en: 'My favorite food is pizza.' },
    { pt: 'Eu moro em São Paulo.', en: 'I live in São Paulo.' },
    { pt: 'Eu trabalho em um escritório.', en: 'I work in an office.' },
    { pt: 'O banheiro está ali.', en: 'The bathroom is over there.' },
    { pt: 'A estação de trem fica na próxima rua.', en: 'The train station is on the next street.' },
    { pt: 'Eu nasci em Rio de Janeiro.', en: 'I was born in Rio de Janeiro.' },
    { pt: 'O restaurante está na esquina.', en: 'The restaurant is on the corner.' },
    { pt: 'O supermercado mais próximo está a duas quadras daqui.', en: 'The nearest supermarket is two blocks away.' },
    { pt: 'Eu estudei na Universidade de São Paulo.', en: 'I studied at the University of São Paulo.' },
    { pt: 'O ponto de ônibus está naquela direção.', en: 'The bus stop is in that direction.' },
    { pt: 'Eu estava em casa ontem.', en: 'I was at home yesterday.' },    

    { pt: 'Por favor, pode me ajudar?', en: 'Please, can you help me?' },
    { pt: 'Quanto custa isso?', en: 'How much does this cost?' },
    { pt: 'Eu não entendo.', en: 'I don\'t understand.' },
    { pt: 'Você fala inglês?', en: 'Do you speak English?' },
    { pt: 'Eu preciso de um médico.', en: 'I need a doctor.' },
    { pt: 'Onde fica o hotel?', en: 'Where is the hotel?' },
    { pt: 'Pode repetir, por favor?', en: 'Can you repeat, please?' },
    { pt: 'Eu gostaria de uma mesa para duas pessoas.', en: 'I would like a table for two, please.' },
    { pt: 'Qual é o horário de funcionamento?', en: 'What are the opening hours?' },
    { pt: 'Posso pagar com cartão?', en: 'Can I pay with a card?' },
    
    { pt: 'Claro, estou aqui para ajudar.', en: 'Of course, I\'m here to help.' },
        { pt: 'Isso custa R$ 20.', en: 'That costs $20.' },
        { pt: 'Posso explicar de outra forma?', en: 'Can I explain it differently?' },
        { pt: 'Sim, eu falo inglês fluentemente.', en: 'Yes, I speak English fluently.' },
        { pt: 'Vou chamar um médico imediatamente.', en: 'I will call a doctor immediately.' },
        { pt: 'O hotel fica na rua principal.', en: 'The hotel is on the main street.' },
        { pt: 'Claro, eu posso repetir.', en: 'Sure, I can repeat.' },
        { pt: 'Certamente, vou providenciar uma mesa para duas pessoas.', en: 'Certainly, I will arrange a table for two.' },
        { pt: 'Estamos abertos das 9h às 18h, de segunda a sexta-feira.', en: 'We are open from 9am to 6pm, Monday to Friday.' },
        { pt: 'Sim, aceitamos cartões de crédito e débito.', en: 'Yes, we accept credit and debit cards.' } 
    ];
